ALTER TABLE cards 
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active',
ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(12, 2),
ADD COLUMN IF NOT EXISTS credit_used DECIMAL(12, 2) DEFAULT 0.00;