ALTER TABLE cards ADD COLUMN IF NOT EXISTS card_name VARCHAR(100) DEFAULT 'Виртуальная карта';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS card_category VARCHAR(50) DEFAULT 'debit';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS is_child_card BOOLEAN DEFAULT FALSE;